### ISSUE TITLE
cross account functionality

### ISSUE THREAD

**Issue by SeeleyFamily** [intuit/Trapheus#222]
Examining the lambda, the state machine definition, and SSM documents, there is a lot of cross-account functionality built in. Is there any documentation available on how to leverage this? No worries if not, just curious.

I must be wrong, but the way I understand the documented scenarios are:
1) create_snapshot: creates a snapshot, renames the existing RDS instance, creates a new RDS instance with same name from the newly created snapshot, then deletes the existing renamed RDS instance 
2) db_restore: renames an existing RDS instance, creates a new database from an existing snapshot, then deletes the existing renamed RDS instance
3) create_snapshot_only: creates a snapshot from an existing RDS instance, deleting the current snapshot if it exists

I don't understand the usefulness of 1 and 2 out of the box unless you can pass a new DBInstanceIdentifier to restore to (that's what I'm doing). 

It seems like I'm missing something, any light you can shed on the full utility of the lambdas would be greatly appreciated.

Thank you!

**Comment by namitad** [comment]
on the cross-account functionality - there is some testing pending which is why the details of the functionality havent been added to the readme yet - will add it soon. 

the `db_restore` task was the 1st capability added. the thought process here was to restore the same db back to a point-in-time using a snapshot. examples of its usecases could be periodic perf testing on db which adds a lot of data. snapshot can be used to purge all additional data and restore db back to pre-testing phase
the `create_snapshot` task was added from a completeness perspective to enable testing of all the different parts of the pipeline and the complete restore flow.

One of the capabilities we were looking to add was - supporting custom snapshot identifiers (instead of using the latest manual snapshot by default) for these tasks so that users can choose which backup to restore or customise the name of the snapshot according to the task #132, https://github.com/intuit/Trapheus/issues/143. These were not prioritised so the customisation functionality has not been added yet. 

Similar to this and as you rightly pointed out, we will also look at supporting a user-defined target database identifier.

Will update on this issue once the support is added.  thanks!

@SeeleyFamily additionally - do let me know if you are interested in contributing to any of these issues.

**Comment by SeeleyFamily** [comment]
Thank you for the detailed explanation. This is a great framework and starting point and I've been able to easily modify to fit my scenario as needed.

As an aside, I noted that the Route53 functionality requires a DNS endpoint to create the CNAME record. What I am looking to create is a Lambda that will grab the current DNS endpoint (derived from describe_db_instances), and create a new CNAME record with it as the value, deleting the current CNAME record if it exists. I'll let you know how it goes, it would be a great compliment to the existing suite of Lambdas. Thanks!
