### ISSUE TITLE
Trapheus exporting and restoring to other AWS accounts

### ISSUE THREAD

**Issue by cnguyen115** [intuit/Trapheus#68]
Is it possible to use Trapheus to automate export + restore databases to different AWS accounts?

For example, I would like to run create_snapshot_only on Account A and run db_restore on Account B using Account's A snapshot

**Comment by namitad** [comment]
@cnguyen115 Trapheus presently supports restoring db from snapshot and export of an RDS instance/cluster to S3 independently. but not the restore to a different account. We are looking to build this capability for within same account and different accounts.
since the files exported to S3 are in apache parquet format, the same can be used for manually creating a db instance by following this: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromS3.html. 
this is what we are looking to add to the pipeline.
Do share your thoughts on whether this is on the lines of what you are looking for.

**Comment by stationeros** [comment]
@namitad Can you assign this issue to me if no one is working on this.

**Comment by stationeros** [comment]
This change in a nutshell would require introducing a new lambda for exporting the snapshot to a target account id. Did try this on my local machine, and was able to successfully export the snapshot into a separate account, although we do need a cleaner way of passing in the target_account_id from the start to the lambda that ships the snapshot to the different account. 

Still on the lookout for a more elegant way to stop the state machine execution post the snapshot export from the lambda.

@namitad  is it possible to break this issue into two for cluster and individual database instances?

**Comment by stationeros** [comment]
Re-opening this - as @namitad  is working on this
